name: Build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - uses: actions/checkout@v2.3.2 

      - name: Install esy
        run: npm install -g esy@beta

      - name: Try to restore install cache
        uses: actions/cache@v2.1.1
        with:
          path: ~/.esy/source
          key: 2023090201-source-${{ hashFiles('**/index.json') }}

      - name: esy i
        run: esy i

      - name: esy build --release
        run: esy build --release

      - name: Test
        run: esy test

      - name: Test node bindings
        run: esy test-js

      - name: Test ts declaration
        run: esy test-ts

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: orange_diff_generated
          path: test/test-images

      - name: Build docs
        run: esy doc
